=== Liudmila-T/Practice7/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--  XML schema -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://nure.ua/timoshenko/practice7"
            xmlns:tns="http://nure.ua/timoshenko/practice7">

    <xsd:element name="Medicines">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Medicine"
                             type="tns:Medicine" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="Medicine">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="Pharm" type="xsd:string"/>
            <xsd:element name="Group" type="xsd:string"/>
            <xsd:sequence>
                <xsd:element name="Analogs"
                             type="xsd:string" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:element name="Versions"
                         type="tns:Versions" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Versions">
        <xsd:sequence>
            <xsd:element name="nameVersions" type="xsd:string"/>
            <xsd:element name="Manufacturer"
                         type="tns:Manufacturer" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Manufacturer">
        <xsd:sequence>
            <xsd:element name="nameManufacturer" type="xsd:string"/>
            <xsd:element name="Certificate"
                         type="tns:Certificate" maxOccurs="1"/>
            <xsd:element name="Package"
                         type="tns:Package" maxOccurs="unbounded"/>
            <xsd:element name="dosage" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Certificate">
        <xsd:sequence>
            <xsd:element name="number" type="xsd:int"/>
            <xsd:element name="date" type="xsd:date"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Package">
        <xsd:sequence>
            <xsd:element name="type" type="xsd:string"/>
            <xsd:element name="quantity" type="xsd:int"/>
            <xsd:element name="price" type="xsd:double"/>

        </xsd:sequence>
    </xsd:complexType>


</xsd:schema>

=== Liudmila-T/Practice7/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--  Input XML document. This XML is valid against Test.xsd XML schema-->

<p7:Medicines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xmlns:p7="http://nure.ua/timoshenko/practice7"
     xsi:schemaLocation="http://nure.ua/timoshenko/practice7 input.xsd">

    <Medicine>
    <name>Nuroffen</name>
        <Pharm>NMN</Pharm>
        <Group>painkillers</Group>
        <Analogs>Ibuprofen</Analogs>
        <Analogs>Paracetamol</Analogs>
        <Versions>
            <nameVersions>pills</nameVersions>
            <Manufacturer>
                <nameManufacturer>Farmac</nameManufacturer>
                <Certificate>
                    <number>11111</number>
                    <date>2013-12-12</date>
                </Certificate>
                <Package>
                    <type>box</type>
                    <quantity>10</quantity>
                    <price>100</price>
                </Package>
                <dosage>1x3times/day</dosage>
            </Manufacturer>
            <Manufacturer>
                <nameManufacturer>Farmac</nameManufacturer>
                <Certificate>
                    <number>11111</number>
                    <date>2013-12-12</date>
                </Certificate>
                <Package>
                    <type>box</type>
                    <quantity>10</quantity>
                    <price>100</price>
                </Package>
                <dosage>1x3times/day</dosage>
            </Manufacturer>
        </Versions>
        <Versions>
            <nameVersions>powder</nameVersions>
            <Manufacturer>
                <nameManufacturer>Zdorovya</nameManufacturer>
                <Certificate>
                    <number>22222</number>
                    <date>2013-12-12</date>
                </Certificate>
                <Package>
                    <type>box</type>
                    <quantity>20</quantity>
                    <price>200</price>
                </Package>
                <dosage>1x3times/day</dosage>
            </Manufacturer>
            <Manufacturer>
                <nameManufacturer>ZZZ</nameManufacturer>
                <Certificate>
                    <number>3333</number>
                    <date>2013-12-12</date>
                </Certificate>
                <Package>
                    <type>box</type>
                    <quantity>30</quantity>
                    <price>300</price>
                </Package>
                <dosage>1x3times/day</dosage>
            </Manufacturer>
        </Versions>
            </Medicine>
    <Medicine>
    <name>LizaK</name>
    <Pharm>Medic</Pharm>
    <Group>painkillers</Group>
    <Analogs>Lisobact</Analogs>
    <Analogs>Ingalipt</Analogs>
    <Versions>
        <nameVersions>capsules</nameVersions>
        <Manufacturer>
            <nameManufacturer>Farmac</nameManufacturer>
            <Certificate>
                <number>33333</number>
                <date>2013-12-12</date>
            </Certificate>
            <Package>
                <type>box</type>
                <quantity>10</quantity>
                <price>130</price>
            </Package>
            <dosage>1x3times/day</dosage>
        </Manufacturer>
    </Versions>
    <Versions>
        <nameVersions>powder</nameVersions>
        <Manufacturer>
            <nameManufacturer>Zdorovya</nameManufacturer>
            <Certificate>
                <number>44444</number>
                <date>2014-01-16</date>
            </Certificate>
            <Package>
                <type>box</type>
                <quantity>20</quantity>
                <price>250</price>
            </Package>
            <dosage>1x3times/day</dosage>
        </Manufacturer>
        <Manufacturer>
            <nameManufacturer>ZZZ</nameManufacturer>
            <Certificate>
                <number>3333</number>
                <date>2001-01-18</date>
            </Certificate>
            <Package>
                <type>box</type>
                <quantity>40</quantity>
                <price>400</price>
            </Package>
            <dosage>1x3times/day</dosage>
        </Manufacturer>
    </Versions>
</Medicine>
</p7:Medicines>
